name: etakesh_client
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons. map 0.4.0
  cupertino_icons: ^0.1.2
  #google_maps_flutter: ^0.4.0
  #location: ^1.4.1
  #http: ^0.12.0+1
  google_maps_flutter: ^0.5.6
  #location: ^2.3.5
  google_maps_webservice: ^0.0.14
  geolocator: 3.0.1
  http: ^0.12.0+2
  sqflite: ^1.1.0
  path_provider: ^0.5.0+1
  shared_preferences: ^0.4.2
  #country_pickers: ^1.0.0
  google_sign_in: ^4.0.0
  #firebase_auth: ^0.6.6
  firebase_auth: ^0.8.4+5
  #flutter_google_places: ^0.2.2
  positioned_tap_detector: ^1.0.2
  flutter_local_notifications: 0.6.0
  intl: ^0.15.8
  image_picker: ^0.6.1+4
  # image_picker: ^0.5.4+3
  barcode_scan: ^1.0.0
  dio: 2.1.13
  cached_network_image: ^1.1.1
  geocoder: ^0.2.1
  # cached_network_image: 0.7.0
  # flutter_cache_manager: 0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/presentation/Present1.png
   - assets/images/presentation/Present2.png
   - assets/images/presentation/Present3.png
   - assets/images/presentation/Present4.png
   - assets/images/avatar.png
   - assets/images/login_icon.png
   - assets/images/google.png
   - assets/images/facebook.png
   - assets/images/cameroun_flag.png
   - assets/images/taxi_icon.png
   - assets/images/qr_code.png
   - assets/images/work.png
   - assets/images/home.png
   - assets/images/ok.gif
   - assets/images/stop_taxi.png
   - assets/images/service.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
